[build]
  publish = "wwawing.com"
  command = "npm start"

[build.environment]
  NODE_VERSION = "22.20.0"
  NPM_VERSION = "11"

[[redirects]]
  from = "/wing/24life.html"
  to = "https://archive.chashitsu.org/wing/24life/24life.html"

[[redirects]]
  from = "/wing/kuso6.html"
  to = "https://hirarira.net/wwa/kuso/kuso06/"

[[redirects]]
  from = "/wing/moneyXP.html"
  to = "https://archive.chashitsu.org/wing/moneyxp.html"

[[redirects]]
  from = "/wing/seikatsu.html"
  to = "https://archive.chashitsu.org/wing/seikatsu.html"

[[redirects]]
  from = "/wing/spaceisland.html"
  to = "https://archive.chashitsu.org/wing/seikatsu.html"

[[redirects]]
  from = "/wwaaa/*"
  to = "https://old-experiments.wwawing.com/wwaaa/:splat"

[[redirects]]
  from = "/wing-x/*"
  to = "https://old-experiments.wwawing.com/wing-x/:splat"

[[redirects]]
  from = "/wwap"
  to = "https://wwaphoenix.github.io/"

[[redirects]]
  from ="/acorn-statement/*"
  to = "/unstable/:splat"
